### ISSUE TITLE
Support multiple paths

### ISSUE THREAD

**Issue by marverix** [DataDog/junit-upload-github-action#21]
Is it possible to support multiple paths? With Gradle builds you can have unit tests reports in each component path.

**Comment by juan-fernandez** [comment]
hey @marverix this should be supported by doing something like:

```yaml
      - uses: datadog/junit-upload-github-action@v1
        with:
          api-key: ${{ secrets.DD_API_KEY }}
          service: my-custom-service
          files: ./folder-1 ./folder-2
```

I'm closing this issue, but feel free to reopen if this doesn't work for you
