### ISSUE TITLE
NodeJS version no longer defaulting to 20

### ISSUE THREAD

**Issue by eliprand** [DataDog/junit-upload-github-action#23]
Not 100% sure what is happening. I can do some more digging as to when this started exactly.
But for now, the action is defaulting to NodeJS 16. We're pretty sure this used to work properly a few months ago when we started using this action. Here is how we are calling the action:
```yaml
      - name: Upload Test Results to Datadog
        if: ${{ !cancelled()}}
        uses: datadog/junit-upload-github-action@v1
        with:
          api-key: ${{ secrets.DATADOG_API_TOKEN }}
          service: luminosity
          files: ./**/build/test-results/test/*.xml
```

When it's executing, we get the following:

![Image](https://github.com/user-attachments/assets/f49bc653-e226-4ba9-940e-c0af6a858f32)

You can see that the `node-version` gets set to 16 while we did not specify it, expecting it to use `20` as the documentation states.

As I write this ticket, the interesting thing too is that our action seems to use `actions/setup-node@v3` based on the logs. However, the code in this repo seems to be using `v4` for at least 8 months... Any idea what is going on?
