### ISSUE TITLE
Undeclared input dd-env is used

### ISSUE THREAD

**Issue by martinmosegaard** [DataDog/junit-upload-github-action#5]
Version: v1.1.0

The inputs declare:

```
  env:
    required: false
    description: Datadog env to use for the tests.
```

But passing `env` has no effect, since it is not actually used, but instead `dd-env` is:

```
      env:
        DATADOG_API_KEY: ${{ inputs.api-key }}
        DATADOG_SITE: ${{ inputs.datadog-site }}
        DD_ENV: ${{ inputs.dd-env }}
```

From a caller workflow, passing `dd-env` _does_ work, but results in a warning in the GitHub actions summary:

```
Unexpected input(s) 'dd-env', valid inputs are ['api-key', 'service', 'datadog-site', 'files', 'concurrency', 'node-version', 'tags', 'env', 'logs']
```

On the Datadog side, some pages like `ci/test-branch` expect a query param `env` or they will show a big *Arf. 404 Page Not Found*. So it is hard to link to a page specific to one project and one branch.

Workaround for now seems to be to use `env=none` in Datadog link.
